use AdventureWorks2012

--QUANTOS PRODUTOS VERMELHOS TEM PRECO ENTRE 500 E 1000 USD

SELECT COUNT(ListPrice) AS 'PRODUTOS DE COR VERMELHA' FROM Production.Product
WHERE ListPrice BETWEEN 500 AND 1000 
AND Color = 'red'

--PRODUTOS QUE TEM ESSA SEQ DE CARACTER NO NOME ROAD


SELECT COUNT(Name) FROM Production.Product
WHERE Name LIKE '%ROAD%'

SELECT TOP 10 * FROM SALES.SalesOrderDetail

SELECT TOP 10 MAX(LINETOTAL) AS 'TOTAL VENDAS'
FROM Sales.SalesOrderDetail

SELECT FirstName, COUNT(FIRSTNAME) AS QNTDE FROM Person.Person
GROUP BY FirstName

SELECT SpecialOfferID, SUM(UnitPrice) FROM Sales.SalesOrderDetail
GROUP BY SpecialOfferID
ORDER BY SUM(UnitPrice) DESC

--QUANTOS PRODUTOS FORAM VENDIDOS ATÉ HJ

SELECT * FROM Production.Product
SELECT * FROM Sales.SalesOrderDetail
SELECT ProductId, COUNT(OrderQty) AS 'QNT DE CADA PRODUTOS' FROM Sales.SalesOrderDetail
GROUP BY ProductID

--PRODUCTION.PRODUCT - PRODUTOS PRATA - SILVER / MEDIA PREÇO - LISTPRICE

SELECT * FROM Production.Product
SELECT Color, AVG(ListPrice) FROM Production.Product
WHERE Color = 'SILVER'
GROUP BY Color


-- QNTS PESSOAS TEM O MSM MIDLE NAME E QUAIS SÃO
SELECT MiddleName, COUNT(MiddleName) FROM Person.Person
GROUP BY MiddleName
ORDER BY MiddleName

--DESAFIOS
--1 - QUAL A MEDIA QUE CADA PRODUTO É VENDIDO

SELECT * FROM Sales.SalesOrderDetail
SELECT ProductID, AVG(OrderQty) FROM Sales.SalesOrderDetail
GROUP BY ProductID

--2 - QUAIS OS 10 PRODUTOS QUE NO TOTAL TIVERAM OS MAIORES VALORES DE VENDA AGRUPADOS POR PRODUTO DO MAIOR PARA O MENOR

SELECT TOP 10 ProductID, SUM(LineTotal) FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY SUM(LineTotal) DESC

--3 - QUANTOS PRODUTOS E QUAL A QNTDE MEDIA DE PRODUTOS TEMOS CADASTRADOS NAS ORDENS DE SERVICO(WORKORDER) - AGRUPAR PELO ID DO PRODUTO 

SELECT * FROM Production.WorkOrder
SELECT ProductID, COUNT(ProductID) AS 'QNTD', AVG(ORDERQTY) AS 'MEDIA' FROM Production.WorkOrder
GROUP BY ProductID


--HAVING PESQUISA NO GROUP BY/NO AGRUPAMENTO

SELECT FirstName, COUNT(FirstName) FROM Person.Person
WHERE FirstName LIKE 'A%'
GROUP BY FirstName
HAVING COUNT(FirstName) > 10

--AGRUPAR PRODUTOS POR VENDAS TOTAIS ENTRE 162K E 500K

SELECT ProductID, SUM(LineTotal) FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING SUM(LineTotal) BETWEEN 162000 AND 500000

-- QUAIS PRODUTOS NÃO ESTÃO TRAZENDO EM MEDIAS VENDAS DE 100k

SELECT * FROM Sales.SalesOrderDetail
SELECT ProductID, AVG(LineTotal) FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING AVG(LineTotal) < 1000
